language: php

os: linux

dist: bionic

php:
    - 7.2
    - 7.3
    - 7.4

env:
    -
        SYMFONY_VERSION=4.4.*
        STATE_MACHINE_VERSION=^0.3.2
        TWIG_VERSION=^2.12
    -
        SYMFONY_VERSION=4.4.*
        STATE_MACHINE_VERSION=^0.4.3
        TWIG_VERSION=^3.0
    -
        SYMFONY_VERSION=4.4.*
        STATE_MACHINE_VERSION=^0.5
        TWIG_VERSION=^3.0
    -
        SYMFONY_VERSION=5.0.*
        STATE_MACHINE_VERSION=^0.5
        TWIG_VERSION=^3.0

jobs:
    fast_finish: true

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=6144M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
    - composer config extra.symfony.require "${SYMFONY_VERSION}"
    - (cd src/Component && composer config extra.symfony.require "${SYMFONY_VERSION}")

install:
    - composer require winzou/state-machine-bundle:$STATE_MACHINE_VERSION --no-update --no-scripts --prefer-dist
    - composer require twig/twig:$TWIG_VERSION --dev --no-update --no-scripts --prefer-dist
    - composer update --prefer-dist --no-scripts

    - (cd src/Component && composer update --prefer-dist --no-scripts)

before_script:
    - (cd src/Bundle/test && app/console doctrine:database:create)
    - (cd src/Bundle/test && app/console doctrine:schema:create)

script:
    - composer validate --strict
    - (cd src/Component && composer validate --strict)

    - composer analyse

    - vendor/bin/phpspec run
    - (cd src/Component && vendor/bin/phpspec run)

    - vendor/bin/phpunit

    - composer require doctrine/orm:^2.5 --no-update --no-scripts --prefer-dist
    - composer update --no-dev --prefer-dist
    - (cd src/Bundle/test && app/console cache:clear --env=prod)
